services:
  api:
    build:
      context: .
      target: dev
    image: job-parser/api:dev
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - pgdata-dev:/var/lib/postgresql/data

volumes: 
  pgdata-dev:
