services:
  api:
    build:
      context: .
      target: prod
    image: job-parser/api:prod
    environment:
      NODE_ENV: production
    ports:
      - "3000:80"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
